version: '2'
services:
  influxdb:
    image: influxdb:1.2-alpine
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:4.2.0
    ports:
      - 3000:3000
